// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFn-HaLa1b3NncL443VpttU_ySWEE4joI',
    appId: '1:232016685845:web:90bf4e9de500cd9c23171c',
    messagingSenderId: '232016685845',
    projectId: 'hotel-management-system-c83ad',
    authDomain: 'hotel-management-system-c83ad.firebaseapp.com',
    storageBucket: 'hotel-management-system-c83ad.firebasestorage.app',
    measurementId: 'G-KJLE5ZCYB1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpk6vCmz-DR6rBFfNViicjVHpJ2LTuzN8',
    appId: '1:232016685845:android:5514a51527e0116d23171c',
    messagingSenderId: '232016685845',
    projectId: 'hotel-management-system-c83ad',
    storageBucket: 'hotel-management-system-c83ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy7u9rkUqtBlY-Uo_Cl4WO8bZ7Bfd45Dc',
    appId: '1:232016685845:ios:c9ba5c8f50ee5f2023171c',
    messagingSenderId: '232016685845',
    projectId: 'hotel-management-system-c83ad',
    storageBucket: 'hotel-management-system-c83ad.firebasestorage.app',
    iosBundleId: 'com.example.hms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy7u9rkUqtBlY-Uo_Cl4WO8bZ7Bfd45Dc',
    appId: '1:232016685845:ios:c9ba5c8f50ee5f2023171c',
    messagingSenderId: '232016685845',
    projectId: 'hotel-management-system-c83ad',
    storageBucket: 'hotel-management-system-c83ad.firebasestorage.app',
    iosBundleId: 'com.example.hms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFn-HaLa1b3NncL443VpttU_ySWEE4joI',
    appId: '1:232016685845:web:e5d862fb63314d3f23171c',
    messagingSenderId: '232016685845',
    projectId: 'hotel-management-system-c83ad',
    authDomain: 'hotel-management-system-c83ad.firebaseapp.com',
    storageBucket: 'hotel-management-system-c83ad.firebasestorage.app',
    measurementId: 'G-W467VMV8JB',
  );
}
